### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by eth030** [npmSteven/Unraid-VM-CP#1]
after installing it on unraid
login in to the 8786->frontend
i get an popup unable to login to unraid.

**Comment by npmSteven** [comment]
Did you enter your unraid ip correctly in the edit app page. 
It should look something like this
![image](https://user-images.githubusercontent.com/28809905/222448438-ed91dbff-c082-4a16-bd2b-4cf8d28897aa.png)

**Comment by AkashRajvanshi** [comment]
getting same, unable to login.

**Comment by npmSteven** [comment]
> getting same, unable to login. 

Weird could you possibly send me a screenshot of your app edit page 
https://youtu.be/3IrtI1_v2OI

**Comment by AkashRajvanshi** [comment]
![Screenshot_2023-03-03-10-32-10_1920x1080](https://user-images.githubusercontent.com/30198030/222635740-123a637f-7dd8-458b-b899-8961b1bc60d5.png)

**Comment by npmSteven** [comment]
@AkashRajvanshi would it be possible to have a quick call? I have discord Noisy#0001 or google meet.

**Comment by npmSteven** [comment]
I have not received any issues from other members about this issue for now I will consider it closed.
